<select class="t1-select" id="user_lang" name="user[lang]">
<option>Select Language...</option>
<option value="id">Bahasa Indonesia - Indonesian</option>
<option value="msa">Bahasa Melayu - Malay</option>
<option value="ca">Català - Catalan (beta)</option>
<option value="cs">Čeština - Czech</option>
<option value="da">Dansk - Danish</option>
<option value="de">Deutsch - German</option>
<option value="en" selected="">English</option>
<option value="en-gb">English UK - British English</option>
<option value="es">Español - Spanish</option>
<option value="eu">Euskara - Basque (beta)</option>
<option value="fil">Filipino</option>
<option value="fr">Français - French</option>
<option value="ga">Gaeilge - Irish (beta)</option>
<option value="gl">Galego - Galician (beta)</option>
<option value="hr">Hrvatski - Croatian (beta)</option>
<option value="it">Italiano - Italian</option>
<option value="xx-lc">LOLCATZ - Lolcat (beta)</option>
<option value="hu">Magyar - Hungarian</option>
<option value="nl">Nederlands - Dutch</option>
<option value="no">Norsk - Norwegian</option>
<option value="pl">Polski - Polish</option>
<option value="pt">Português - Portuguese</option>
<option value="ro">Română - Romanian</option>
<option value="sk">Slovenčina - Slovak (beta)</option>
<option value="fi">Suomi - Finnish</option>
<option value="sv">Svenska - Swedish</option>
<option value="vi">Tiếng Việt - Vietnamese</option>
<option value="tr">Türkçe - Turkish</option>
<option value="el">Ελληνικά - Greek</option>
<option value="bg">Български език - Bulgarian (beta)</option>
<option value="ru">Русский - Russian</option>
<option value="sr">Српски - Serbian (beta)</option>
<option value="uk">Українська мова - Ukrainian</option>
<option value="he">עִבְרִית - Hebrew</option>
<option value="ur">اردو - Urdu (beta)</option>
<option value="ar">العربية - Arabic</option>
<option value="fa">فارسی - Persian</option>
<option value="mr">मराठी - Marathi</option>
<option value="hi">हिन्दी - Hindi</option>
<option value="bn">বাংলা - Bengali</option>
<option value="gu">ગુજરાતી - Gujarati</option>
<option value="ta">தமிழ் - Tamil</option>
<option value="kn">ಕನ್ನಡ - Kannada</option>
<option value="th">ภาษาไทย - Thai</option>
<option value="ko">한국어 - Korean</option>
<option value="ja">日本語 - Japanese</option>
<option value="zh-cn">简体中文 - Simplified Chinese</option>
<option value="zh-tw">繁體中文 - Traditional Chinese</option>
</select>